import { getRenditionStorageStatus, runRenditionCleanup, saveRenditionPolicy, type RenditionStoragePolicy, type RenditionStorageStatus } from "../api/renditionPolicyApi";
import { RENDITION_PROFILE_IDS } from "../shared/renditionTypes";
import "./renditionStorageAdmin.css";

const bytes = (value: number | null) => value === null ? "Unavailable" : new Intl.NumberFormat(undefined, { style: "unit", unit: "gigabyte", maximumFractionDigits: 1 }).format(value / 1e9);
const field = (label: string, name: string, value: number | null, min: number, max: number) => `<label><span>${label}</span><input name="${name}" type="number" min="${min}" max="${max}" value="${value ?? ""}" placeholder="Unlimited"></label>`;
export const renderRenditionStorageAdmin = () => `<section class="rendition-storage-admin diagnostic-section" data-diagnostic-section="rendition-storage" aria-live="polite"><div class="rendition-storage-heading"><div><h3>Rendition Storage</h3><p>Manage reusable video quality output, capacity, retention, and cleanup.</p></div><button type="button" data-rendition-refresh>Refresh</button></div><div data-rendition-storage-content><p>Loading rendition storage…</p></div><span data-rendition-storage-message></span></section>`;
const render = (status: RenditionStorageStatus) => {
  const p = status.policy;
  const cache = status.usage.groups.filter((g) => g.retention === "cache").reduce((n,g) => n + g.bytes, 0);
  const pinned = status.usage.groups.filter((g) => g.retention === "pinned").reduce((n,g) => n + g.bytes, 0);
  return `<div class="rendition-storage-summary"><span><small>Ready output</small><strong>${bytes(status.usage.totalReadyBytes)}</strong></span><span><small>Cache</small><strong>${bytes(cache)}</strong></span><span><small>Pinned</small><strong>${bytes(pinned)}</strong></span><span><small>Disk free</small><strong>${bytes(status.disk.freeBytes)}</strong></span></div>
  <form data-rendition-policy><div class="rendition-storage-fields">${field("Quota bytes", "quotaBytes", p.quotaBytes, 1048576, 1125899906842624)}${field("Minimum free bytes", "minimumFreeBytes", p.minimumFreeBytes, 0, 1125899906842624)}${field("High water %", "highWaterPercent", p.highWaterPercent, 50, 99)}${field("Low water %", "lowWaterPercent", p.lowWaterPercent, 25, 98)}${field("Maximum cache age (days)", "maxCacheAgeDays", p.maxCacheAgeDays, 1, 3650)}${field("Failed record retention (days)", "failedRecordDays", p.failedRecordDays, 1, 3650)}${field("Stale record retention (days)", "staleRecordDays", p.staleRecordDays, 1, 3650)}${field("Cleanup interval (minutes)", "cleanupIntervalMinutes", p.cleanupIntervalMinutes, 5, 10080)}${field("Cleanup batch size", "cleanupBatchSize", p.cleanupBatchSize, 1, 1000)}</div>
  <fieldset><legend>Scheduled profiles</legend>${RENDITION_PROFILE_IDS.map(id => `<label><input type="checkbox" name="profile" value="${id}" ${p.allowedProfileIds.includes(id) ? "checked" : ""}>${id}</label>`).join("")}</fieldset>
  <label class="rendition-storage-toggle"><input type="checkbox" name="cacheInteractive" ${p.cacheInteractive ? "checked" : ""}>Cache interactive transcodes</label><label class="rendition-storage-toggle"><input type="checkbox" name="pinScheduledByDefault" ${p.pinScheduledByDefault ? "checked" : ""}>Pin scheduled builds by default</label>
  <div class="rendition-storage-actions"><button type="submit">Save policy</button><button type="button" data-rendition-cleanup>Run cleanup</button></div></form>`;
};
const read = (form: HTMLFormElement): RenditionStoragePolicy => {
  const data = new FormData(form); const number = (name: string, nullable = false) => { const raw=String(data.get(name)??"").trim(); return nullable && !raw ? null : Number(raw); };
  return { allowedProfileIds: data.getAll("profile").map(String), cacheInteractive: data.has("cacheInteractive"), cleanupBatchSize: number("cleanupBatchSize")!, cleanupIntervalMinutes: number("cleanupIntervalMinutes")!, failedRecordDays: number("failedRecordDays")!, highWaterPercent: number("highWaterPercent")!, lowWaterPercent: number("lowWaterPercent")!, maxCacheAgeDays: number("maxCacheAgeDays", true), minimumFreeBytes: number("minimumFreeBytes")!, pinScheduledByDefault: data.has("pinScheduledByDefault"), quotaBytes: number("quotaBytes", true), staleRecordDays: number("staleRecordDays")! };
};
export const bindRenditionStorageAdmin = (container: ParentNode) => {
  const root=container.querySelector<HTMLElement>(".rendition-storage-admin"), content=root?.querySelector<HTMLElement>("[data-rendition-storage-content]"), message=root?.querySelector<HTMLElement>("[data-rendition-storage-message]"); if(!root||!content||!message)return()=>{}; let disposed=false;
  const show=(text:string)=>{message.textContent=text;};
  const load=async()=>{try{const status=await getRenditionStorageStatus();if(disposed)return;content.innerHTML=render(status);const form=content.querySelector<HTMLFormElement>("[data-rendition-policy]");form?.addEventListener("submit",async(e)=>{e.preventDefault();show("Saving policy…");try{await saveRenditionPolicy(read(form));await load();show("Rendition policy saved.");}catch(error){show(error instanceof Error?error.message:"Policy could not be saved.");}});content.querySelector<HTMLButtonElement>("[data-rendition-cleanup]")?.addEventListener("click",async(event)=>{const button=event.currentTarget as HTMLButtonElement;if(button.dataset.confirm!=="true"){button.dataset.confirm="true";button.textContent="Confirm cleanup";show("Confirm cleanup. Pinned output will be preserved.");return;}button.disabled=true;show("Queueing cleanup…");try{const result=await runRenditionCleanup();show(result.created?"Cleanup queued.":"Cleanup is already queued or running.");}catch(error){show(error instanceof Error?error.message:"Cleanup could not be queued.");}finally{button.disabled=false;button.dataset.confirm="false";button.textContent="Run cleanup";}});}catch(error){show(error instanceof Error?error.message:"Storage status could not be loaded.");}};
  root.querySelector("[data-rendition-refresh]")?.addEventListener("click",()=>void load());void load();return()=>{disposed=true;};
};
