import { getAccelerationStatus, refreshAcceleration, saveAccelerationMode, type AccelerationStatus } from "../api/transcodeAccelerationApi";
import "./transcodeAccelerationAdmin.css";

export const renderTranscodeAccelerationAdmin = () => `
  <section class="transcode-acceleration-admin diagnostic-section" data-diagnostic-section="transcode-acceleration" aria-live="polite">
    <div class="acceleration-heading"><div><h3>Transcode Acceleration</h3><p>Server-authored optional hardware encoding with deterministic software fallback.</p></div><button type="button" data-acceleration-refresh>Probe now</button></div>
    <form data-acceleration-form><label>Configured mode<select name="mode"><option value="software-only">Software only</option><option value="disabled">Disabled</option><option value="auto">Auto</option><option value="prefer-vaapi">Prefer VAAPI</option><option value="require-vaapi">Require VAAPI</option><option value="prefer-nvenc">Prefer NVIDIA NVENC</option><option value="require-nvenc">Require NVIDIA NVENC</option><option value="prefer-videotoolbox">Prefer VideoToolbox</option><option value="require-videotoolbox">Require VideoToolbox</option></select></label><button type="submit">Save mode</button></form>
    <div data-acceleration-content><p>Loading acceleration status…</p></div><p class="acceleration-remediation">Hardware is optional. If unavailable, keep Software only or a Prefer mode. Linux VAAPI needs a render device; NVIDIA needs Container Toolkit GPU access. Docker Desktop on macOS does not expose macOS VideoToolbox to this Linux container.</p><span data-acceleration-message></span>
  </section>`;
const renderStatus = (status: AccelerationStatus) => `<div class="acceleration-summary"><span><small>Selected backend</small><strong>${status.selectedBackend}</strong></span><span><small>Self-test decision</small><strong>${status.decision}</strong></span><span><small>Active jobs</small><strong>${status.active.hardware} hardware · ${status.active.software} software</strong></span><span><small>Last probe</small><strong>${status.lastProbeAt ? new Date(status.lastProbeAt).toLocaleString() : "Not yet"}</strong></span></div><div class="acceleration-backends">${status.backends.map((backend) => `<span><strong>${backend.name}</strong><small>${backend.available ? "Available" : "Unavailable"} · encoder ${backend.encoderDetected ? "found" : "missing"} · device ${backend.deviceDetected ? "ready" : "unavailable"} · self-test ${backend.selfTest}</small></span>`).join("")}</div>`;
export const bindTranscodeAccelerationAdmin = (container: ParentNode) => {
  const root = container.querySelector<HTMLElement>(".transcode-acceleration-admin"); const content = root?.querySelector<HTMLElement>("[data-acceleration-content]"); const message = root?.querySelector<HTMLElement>("[data-acceleration-message]"); const form = root?.querySelector<HTMLFormElement>("[data-acceleration-form]");
  if (!root || !content || !message || !form) return () => {};
  let disposed = false;
  const show = async (operation = getAccelerationStatus) => { try { const status = await operation(); if (disposed) return; content.innerHTML = renderStatus(status); (form.elements.namedItem("mode") as HTMLSelectElement).value = status.mode; } catch (error) { message.textContent = error instanceof Error ? error.message : "Acceleration status unavailable."; } };
  form.addEventListener("submit", (event) => { event.preventDefault(); message.textContent = "Saving…"; void show(() => saveAccelerationMode(String(new FormData(form).get("mode")))).then(() => { message.textContent = "Acceleration mode saved."; }); });
  root.querySelector("[data-acceleration-refresh]")?.addEventListener("click", () => { message.textContent = "Probing…"; void show(refreshAcceleration).then(() => { message.textContent = "Probe complete."; }); });
  void show(); const timer = window.setInterval(() => { if (!root.hidden) void show(); }, 10_000); return () => { disposed = true; window.clearInterval(timer); };
};
